# Generated by Django 3.1 on 2020-08-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200814_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='html_class',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
